# Generated by Django 4.1.4 on 2022-12-26 09:35

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models

import ai_django.ai_core.validators.schema


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('model', models.CharField(choices=[('Race', 'Regata'), ('Participant', 'Participación'), ('Entity', 'Club')], max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar')], max_length=50)),
                ('changes', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, validators=[
                    ai_django.ai_core.validators.schema.JSONSchemaValidator(
                        schema={'$schema': 'http://json-schema.org/schema#', 'name': 'KeyValue',
                                'properties': {'key': {'type': 'string'}, 'value': {'type': 'string'}}, 'required': ['key', 'value']})]),
                                                                      default=list, size=None)),
            ],
            options={
                'verbose_name': 'Petición',
                'verbose_name_plural': 'Peticiones',
                'db_table': 'request',
            },
        ),
    ]
