# Generated by Django 4.1.1 on 2022-09-14 13:48

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models

import apps.entities.models
import utils.choices


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('to_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                (
                    'other_names',
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None)
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            (utils.choices.ENTITY_CLUB, 'Club'), (utils.choices.ENTITY_LEAGUE, 'Liga'),
                            (utils.choices.ENTITY_FEDERATION, 'Federación'), (utils.choices.ENTITY_PRIVATE, 'Privada')
                        ],
                        max_length=50
                    )
                ),
                ('symbol', models.CharField(null=True, blank=True, default=None, max_length=10)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entity',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('to_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='entities.league')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
            ],
            options={
                'verbose_name': 'Liga',
                'db_table': 'league',
                'ordering': ['name']
            },
        ),
    ]
