# Generated by Django 4.1.3 on 2022-11-08 14:39

from django.db import migrations, models
from django.db.models import F


def copy_field(apps, schema):
    Entity = apps.get_model('entities', 'Entity')
    Entity.objects.all().update(official_name=F('name'))


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0002_entitytitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={
                'ordering': ['type', 'name'],
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades'
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='official_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(copy_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='entity',
            name='official_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
