# Generated by Django 4.1.3 on 2022-12-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_entity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytitle',
            name='show_after',
            field=models.BooleanField(default=False),
        ),
    ]
