# Generated by Django 4.2.1 on 2023-06-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0003_remove_entity_title_alter_entity_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='other_names',
            new_name='known_names',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='official_name',
        ),
        migrations.AddField(
            model_name='entity',
            name='fused_into',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='formed_by', related_query_name='formed_by', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_partnership',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='normalized_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='subsidiaries', related_query_name='subsidiary', to='entities.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
