# Generated by Django 4.1.5 on 2023-01-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_entitytitle_show_after'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['id'], 'verbose_name': 'Liga'},
        ),
    ]
