# Generated by Django 4.1.6 on 2023-02-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0005_alter_league_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIX', 'Mixto')], max_length=10),
        ),
    ]
