# Generated by Django 4.2.5 on 2023-10-14 18:41

import django.db.models.deletion
from django.db import migrations, models


def update_entities(apps, schema_editor):
    Entity = apps.get_model("entities", "Entity")
    EntityPartnership = apps.get_model("entities", "EntityPartnership")

    parts = Entity.objects.filter(fused_into__isnull=False).select_related("fused_into")

    for part in parts:
        part.fused_into.is_partnership = True

        EntityPartnership(
            target=part.fused_into,
            part=part,
            is_active=True,
        ).save()
        part.save()


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0006_entitypartnership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitypartnership",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                related_query_name="component",
                to="entities.entity",
            ),
        ),
        migrations.RunPython(update_entities, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="entity",
            name="fused_into",
        ),
    ]
