repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: requirements-txt-fixer
          - id: end-of-file-fixer
          - id: name-tests-test
          - id: check-added-large-files
            exclude: |
                (?x)^(
                    .+h5|
                    fixtures/races-db.yaml
                )$
          - id: check-yaml
          - id: check-toml
          - id: mixed-line-ending
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable

    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.5.0
      hooks:
          - id: setup-cfg-fmt

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.1
      hooks:
          - id: pyupgrade
            args: [--py311-plus]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.1
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
            types_or: [python, pyi]
            exclude: (migrations)
