version: "3.7"
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - redis
  web:
    container_name: r4l-web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        build_command: 'npm run build:dev'
        nginx: 'nginx.dev.conf'
    image: r4l/web
    restart: unless-stopped
    networks:
      - r4l
    ports:
      - '8080:8080'
    volumes:
      - './docker/nginx:/etc/nginx/conf.d'
      - './docker/shared:/srv/www/r4l/shared'
      - './docker/logs:/srv/www/r4l/logs'
      - './docker/sockets:/run/r4l'
  service:
    container_name: r4l-service
    build:
      context: ./service
      dockerfile: Dockerfile
    image: r4l/service
    networks:
      - r4l
      - redis
    volumes:
      - './docker/shared:/srv/www/r4l/shared'
      - './docker/logs:/srv/www/r4l/logs'
      - './docker/sockets:/run/r4l'
    ports:
      - "5557:5555"
    env_file:
      - '.env.docker'
    depends_on:
      - redis
networks:
  r4l:
    external: false
  redis:
    external: false