version: "3.7"
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - redis
  web:
    container_name: r4l-web
    build:
      context: ./web
      dockerfile: Dockerfile
    image: r4l/web
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './docker/certbot/conf:/etc/letsencrypt'
      - './docker/certbot/www:/var/www/certbot'
      - './docker/nginx:/etc/nginx/conf.d'
      - './docker/shared:/srv/www/r4l/shared'
      - './docker/logs:/srv/www/r4l/logs'
      - './docker/sockets:/run/r4l'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  service:
    container_name: r4l-service
    build:
      context: ./service
      dockerfile: Dockerfile
    image: r4l/service
    networks:
      - redis
    volumes:
      - './docker/shared:/srv/www/r4l/shared'
      - './docker/logs:/srv/www/r4l/logs'
      - './docker/sockets:/run/r4l'
    ports:
      - "5557:5555"
    env_file:
      - '.env'
    depends_on:
      - redis
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - './docker/certbot/conf:/etc/letsencrypt'
      - './docker/certbot/www:/var/www/certbot'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  redis:
    external: false
