# Generated by Django 4.2.4 on 2023-09-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0004_auto_20230706_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="qualifies_for",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to="races.flag"
            ),
        ),
        migrations.AddField(
            model_name="trophy",
            name="qualifies_for",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to="races.trophy"
            ),
        ),
    ]
