# Generated by Django 4.2.7 on 2023-11-18 16:11

from django.db import migrations


def update_gender(apps, schema_editor):
    Race = apps.get_model("races", "Race")
    for race in Race.objects.all():
        new_datasources = []
        print(f"updating race metadata: {race.metadata}")
        for datasource in race.metadata["datasource"]:
            if datasource["values"]:
                datasource["values"].pop("gender", None)
                new_datasources.append(datasource)
                race.metadata["datasource"][0] = datasource
        race.metadata["datasource"] = new_datasources
        print(race.metadata)
        race.save()


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0007_race_gender"),
    ]

    operations = [
        migrations.RunPython(update_gender, reverse_code=migrations.RunPython.noop),
    ]
