# Generated by Django 5.0.6 on 2024-06-13 09:23

from django.db import migrations, models

from rscraping.data.constants import CATEGORY_ALL


def update_category(apps, _):
    Race = apps.get_model("races", "Race")

    for race in Race.objects.select_related("league").prefetch_related("participants").all():
        if race.league and race.league.category:
            race.category = race.league.category
            race.save()
            continue

        participants = list(race.participants.all())
        categories = {p.category for p in participants}

        race.category = CATEGORY_ALL if len(participants) <= 1 or len(categories) > 1 else categories.pop()
        race.save()

class Migration(migrations.Migration):
    dependencies = [
        ("races", "0009_alter_race_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="category",
            field=models.CharField(
                choices=[("ALL", "All"), ("SCHOOL", "School"), ("ABSOLUT", "Absolut"), ("VETERAN", "Veteran")],
                default="ALL",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(update_category, reverse_code=migrations.RunPython.noop),
    ]
