# Generated by Django 5.1.1 on 2024-09-25 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


def update_race_names_to_list(apps, _):
    Race = apps.get_model("races", "Race")
    races = Race.objects.filter(race_name__isnull=False)
    num_races = races.count()
    for idx, race in enumerate(races):
        if race.race_name:
            print(f"{idx+1}/{num_races} updating {race.pk}::{race.race_name}")
            race.race_names = [race.race_name]
            race.save()



class Migration(migrations.Migration):
    dependencies = [
        ("races", "0013_flag_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="race_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, default=list, size=None
            ),
        ),
        migrations.RunPython(update_race_names_to_list, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="race",
            name="race_name",
        ),
    ]
