# Generated by Django 5.1.1 on 2024-10-31 09:11

from django.db import migrations, models

import apps.schemas
import djutils.validators.schema


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0014_race_race_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="metadata",
            field=models.JSONField(
                default=apps.schemas.default_metadata,
                validators=[
                    djutils.validators.schema.JSONSchemaValidator(
                        schema={
                            "$schema": "http://json-schema.org/schema#",
                            "name": "RaceMetadata",
                            "properties": {
                                "datasource": {
                                    "items": {
                                        "additionalProperties": False,
                                        "properties": {
                                            "data": {"type": "object"},
                                            "datasource_name": {"type": "string"},
                                            "date": {"type": "string"},
                                            "ref_id": {"type": "string"},
                                            "values": {"additionalProperties": {"type": "string"}, "type": "object"},
                                        },
                                        "required": ["ref_id", "datasource_name", "values"],
                                        "type": "object",
                                    },
                                    "type": "array",
                                }
                            },
                            "required": ["datasource"],
                        }
                    )
                ],
            ),
        ),
    ]
