# Generated by Django 5.1.6 on 2025-02-07 09:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0016_race_same_as"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="last_checked",
            field=models.DateField(default=datetime.datetime(2025, 2, 7, 9, 43, 27, 572323)),
            preserve_default=False,
        ),
    ]
