# Generated by Django 5.2.1 on 2025-07-22 10:49

from django.db import migrations


def update_race_metadata(apps, _):
    Race = apps.get_model("races", "Race")
    filters = [{"datasource_name": "arc"}]
    races = Race.objects.filter(metadata__datasource__contains=filters, league_id=11)
    num_races = races.count()
    for idx, race in enumerate(races):
        for datasource in race.metadata.get("datasource", []):
            if datasource.get("datasource_name") == "arc":
                print(f"{idx + 1}/{num_races} updating {race.pk}")
                datasource["datasource_name"] = "ete"
                race.save()


def reverse_update_metadata(apps, _):
    Race = apps.get_model("races", "Race")
    filters = [{"datasource_name": "ete"}]
    races = Race.objects.filter(metadata__datasource__contains=filters, league_id=11)
    num_races = races.count()
    for idx, race in enumerate(races):
        for datasource in race.metadata.get("datasource", []):
            if datasource.get("datasource_name") == "ete":
                print(f"{idx + 1}/{num_races} updating {race.pk}")
                datasource["datasource_name"] = "arc"
                race.save()


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0017_flag_last_checked"),
    ]

    operations = [
        migrations.RunPython(update_race_metadata, reverse_code=reverse_update_metadata),
    ]
