# Generated by Django 6.0.4 on 2026-04-28 10:37

from django.db import migrations, models

import apps.schemas
import djutils.validators.schema


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0010_entity_town"),
        ("places", "0001_initial"),
        ("races", "0018_ete_datasource"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="race",
            unique_together={
                ("flag", "league", "flag_edition", "modality", "day"),
                ("trophy", "league", "trophy_edition", "modality", "day"),
            },
        ),
        migrations.AlterField(
            model_name="flag",
            name="metadata",
            field=models.JSONField(
                default=apps.schemas.default_metadata,
                validators=[
                    djutils.validators.schema.JSONSchemaValidator(
                        schema={
                            "$schema": "http://json-schema.org/schema#",
                            "name": "FlagMetadata",
                            "properties": {
                                "datasource": {
                                    "items": {
                                        "additionalProperties": False,
                                        "properties": {
                                            "datasource_name": {"type": "string"},
                                            "ref_id": {"type": "string"},
                                            "ref_name": {"type": "string"},
                                            "values": {"additionalProperties": {"type": "string"}, "type": "object"},
                                        },
                                        "required": ["ref_id", "datasource_name", "values"],
                                        "type": "object",
                                    },
                                    "type": "array",
                                }
                            },
                            "required": ["datasource"],
                        }
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.UniqueConstraint(
                condition=models.Q(("same_as__isnull", True)), fields=("league", "date"), name="unique_race_league_date"
            ),
        ),
    ]
