# Generated by Django 6.0.5 on 2026-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0019_alter_race_unique_together_alter_flag_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="has_weird_speeds",
            field=models.BooleanField(default=False),
        )
    ]
