# Generated by Django 4.1.7 on 2023-03-01 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('datasource', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIX', 'Mixto')], max_length=10)),
                ('race_id', models.CharField(max_length=15)),
                (
                    'status',
                    models.CharField(
                        choices=[('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('ERROR', 'ERROR'), ('SUCCESS', 'SUCCESS')],
                        default='PENDING',
                        max_length=10
                    )
                ),
                ('processed_date', models.DateTimeField(default=None, null=True, blank=True)),
                ('resolved_date', models.DateTimeField(default=None, null=True, blank=True)),
                ('details', models.JSONField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'task',
            },
        ),
    ]
