# Generated by Django 5.0.8 on 2024-08-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0009_league_category"),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="town",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entities",
                related_query_name="entity",
                to="places.town",
            ),
        ),
    ]
