# Generated by Django 4.1.1 on 2022-09-15 09:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0001_initial'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('club_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('laps',
                 django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list,
                                                           size=None)),
                ('lane', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('series', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('club',
                 models.ForeignKey(limit_choices_to={'type': 'CLUB'}, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='participation', related_query_name='participation',
                                   to='entities.entity')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants',
                                           related_query_name='participant', to='races.race')),
                ('disqualified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'participant',
                'ordering': ['race', 'club'],
            },
        ),
    ]
