# Generated by Django 4.1.7 on 2023-03-31 11:25

from django.db import migrations, models

import ai_django.ai_core.validators.schema
import apps.schemas


def update_metadata(apps, schema_editor):
    Race = apps.get_model('races', 'Race')
    races = Race.objects.filter(metadata__datasource__contains=[{"values": {}}])
    for race in races:
        datasource = race.metadata['datasource'][0]
        print(f"updating metadata: {datasource}")
        if race_id := datasource.pop('race_id', None):
            datasource['ref_id'] = race_id
        print(datasource)
        race.metadata['datasource'][0] = datasource

    Race.objects.bulk_update(races, ['metadata'])


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0002_alter_race_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='metadata',
            field=models.JSONField(default=apps.schemas.default_metadata, validators=[
                ai_django.ai_core.validators.schema.JSONSchemaValidator(
                    schema={'$schema': 'http://json-schema.org/schema#', 'name': 'RaceMetadata', 'properties': {'datasource': {
                        'items': {'additionalProperties': False,
                                  'properties': {'datasource_name': {'type': 'string'}, 'ref_id': {'type': 'string'},
                                                 'values': {'additionalProperties': {'type': 'string'}, 'type': 'object'}},
                                  'required': ['datasource_name', 'values'], 'type': 'object'}, 'type': 'array'}},
                            'required': ['datasource']})]),
        ),
        migrations.RunPython(update_metadata, reverse_code=migrations.RunPython.noop),
    ]
