# Generated by Django 4.1.1 on 2022-09-21 14:45

from django.db import migrations, models

import ai_django.ai_core.validators.schema
import apps.races.schemas


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='metadata',
            field=models.JSONField(default=apps.races.schemas.default_race_metadata, validators=[
                ai_django.ai_core.validators.schema.JSONSchemaValidator(
                    schema={'$schema': 'http://json-schema.org/schema#', 'name': 'RaceMetadata', 'properties': {
                        'datasource': {'items': {
                            'properties': {'datasource_name': {'type': 'string'}, 'race_id': {'type': 'string'},
                                           'values': {'items': {
                                               'properties': {'key': {'type': 'string'}, 'value': {'type': 'string'}},
                                               'required': ['key', 'value'], 'type': 'object'}, 'type': 'array'}},
                            'required': ['race_id', 'datasource_name'], 'type': 'object'}, 'type': 'array'}},
                            'required': ['datasource']})]),
        ),
    ]
