# Generated by Django 4.1.3 on 2022-11-08 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0003_race_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True,
                                                            default=list, size=None, editable=False),
        ),
        migrations.AddField(
            model_name='trophy',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True,
                                                            default=list, size=None, editable=False),
        ),
        migrations.AddField(
            model_name='flag',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trophy',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
