# Generated by Django 4.1.3 on 2022-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0004_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')],
                                   default=None, max_length=10, null=True),
        ),
    ]
