# Generated by Django 4.1.3 on 2022-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0005_race_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='modality',
            field=models.CharField(
                choices=[('TRAINERA', 'Trainera'), ('TRAINERILLA', 'Trainerilla'), ('BATE', 'Batel')],
                default='TRAINERA', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('trophy', 'league', 'trophy_edition', 'modality', 'day'),
                             ('flag', 'league', 'flag_edition', 'modality', 'day'), ('league', 'date')},
        ),
    ]
