# Generated by Django 4.1.3 on 2022-11-16 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0006_race_modality'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Participant',),
            ],
            # You're reusing the table, so don't drop it
            database_operations=[],
        )
    ]
