# Generated by Django 4.2.6 on 2023-11-01 17:13

from django.db import migrations, models

from rscraping.data.constants import GENDER_ALL


def update_gender(apps, schema_editor):
    Race = apps.get_model("races", "Race")

    for race in Race.objects.select_related("league").prefetch_related("participants").all():
        if race.league and race.league.gender:
            race.gender = race.league.gender
            race.save()
            continue

        participants = list(race.participants.all())
        genders = {p.gender for p in participants}

        race.gender = GENDER_ALL if len(participants) == 1 or len(genders) > 1 else genders.pop()
        race.save()


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0006_race_associated"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("ALL", "All")], default="ALL", max_length=15
            ),
            preserve_default=False,
        ),
        migrations.RunPython(update_gender, reverse_code=migrations.RunPython.noop),
    ]
