# Generated by Django 4.1.6 on 2023-02-06 14:26

from django.db import migrations, models


def update_modality(apps, schema):
    Race = apps.get_model('races', 'Race')
    veterans = Race.objects.filter(modality='VETERAN')

    for race in veterans:
        race.modality = 'TRAINERA'
        race.save()


class Migration(migrations.Migration):
    dependencies = [
        ('races', '0009_alter_race_modality'),
        ('participants', '0005_participant_category_participant_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='gender',
        ),
        migrations.RunPython(update_modality, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='race',
            name='modality',
            field=models.CharField(
                choices=[('TRAINERA', 'Trainera'), ('TRAINERILLA', 'Trainerilla'), ('BATEL', 'Batel')], default='TRAINERA', max_length=15
            ),
        ),
    ]
