# Generated by Django 5.0.4 on 2024-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0004_alter_penalty_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penalty",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOAT_WEIGHT_LIMIT", "Fuera de peso"),
                    ("COLLISION", "Colisión"),
                    ("COVID_ABSENCE", "Ausencia por COVID-19"),
                    ("COXWAIN_WEIGHT_LIMIT", "Timonel fuera de peso"),
                    ("NO_LINE_START", "Salida sin estacha"),
                    ("NULL_START", "Salida nula"),
                    ("OFF_THE_FIELD", "Fuera de campo"),
                    ("SINKING", "Hundimiento"),
                    ("STARBOARD_TACK", "Virada por estribor"),
                    ("WRONG_LINEUP", "Alineación incorrecta"),
                    ("WRONG_ROUTE", "Ruta/Llegada incorrecta"),
                ],
                default=None,
                max_length=500,
                null=True,
            ),
        ),
    ]
