# Generated by Django 5.0.4 on 2024-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_penalty_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
