# Generated by Django 5.1.1 on 2024-09-25 08:43

import django.contrib.postgres.fields
from django.db import migrations, models


def update_club_names_to_list(apps, _):
    Participant = apps.get_model("participants", "Participant")
    participants = Participant.objects.filter(club_names__isnull=False)
    num_participants = participants.count()
    for idx, participant in enumerate(participants):
        if participant.club_name:
            print(f"{idx+1}/{num_participants} updating {participant.pk}::{participant.club_name}")
            participant.club_names = [participant.club_name]
            participant.save()


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0007_participant_retired_alter_penalty_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="club_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150), blank=True, default=list, size=None
            ),
        ),
        migrations.RunPython(update_club_names_to_list, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="participant",
            name="club_name",
        ),
    ]
