# Generated by Django 5.1.1 on 2024-10-24 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0008_participant_club_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="notes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
    ]
