# Generated by Django 4.1.3 on 2022-11-16 12:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('entities', '0002_entitytitle'),
        ('races', '0007_move_participant_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Participant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('club_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                        ('distance', models.PositiveIntegerField(blank=True, default=None, null=True)),
                        (
                            'laps',
                            django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)
                        ),
                        ('lane', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                        ('series', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                        ('disqualified', models.BooleanField(default=False)),
                        (
                            'club',
                            models.ForeignKey(
                                limit_choices_to={'type': 'CLUB'},
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='participation',
                                related_query_name='participation',
                                to='entities.entity'
                            )
                        ),
                        (
                            'race',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='participants',
                                related_query_name='participant',
                                to='races.race'
                            )
                        ),
                    ],
                    options={
                        'verbose_name': 'Participante',
                        'verbose_name_plural': 'Participantes',
                        'db_table': 'participant',
                        'ordering': ['race', 'club'],
                    },
                ),
            ],
            # You reference an existing table
            database_operations=[],
        ),
    ]
