# Generated by Django 4.2.4 on 2023-08-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='handicap',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
