# Generated by Django 4.1.5 on 2023-01-16 11:22

import django.db.models.deletion
from django.db import migrations, models


def copy_penalties(apps, schema):
    Participant = apps.get_model('participants', 'Participant')
    Penalty = apps.get_model('participants', 'Penalty')

    disqualified = Participant.objects.filter(disqualified=True)
    for participant in disqualified:
        penalty = Penalty(
            participant=participant,
            disqualification=True,
        )
        penalty.save()


class Migration(migrations.Migration):
    dependencies = [
        ('participants', '0002_participant_disqualification_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.PositiveIntegerField(blank=True, default=0)),
                ('disqualification', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default=None, max_length=500, null=True)),
                (
                    'participant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='penalties',
                        related_query_name='penalty',
                        to='participants.participant'
                    )
                ),
            ],
            options={
                'verbose_name': 'Penalización',
                'verbose_name_plural': 'Penalizaciones',
                'db_table': 'penalty',
                'ordering': ['participant'],
            },
        ),
        migrations.RunPython(copy_penalties, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='participant',
            name='disqualification_reasons',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='disqualified',
        ),
    ]
