# Generated by Django 4.1.6 on 2023-02-06 12:29

from django.db import migrations, models


def participant_classification(apps, schema):
    Participant = apps.get_model('participants', 'Participant')
    participants = Participant.objects.select_related('race', 'race__league').all()

    for participant in participants:
        participant.gender = participant.race.league.gender \
            if participant.race.league and participant.race.league.gender \
            else participant.race.gender or 'MALE'
        participant.category = 'VETERAN' if participant.race.modality == 'VETERAN' else 'ABSOLUT'
        participant.save()


class Migration(migrations.Migration):
    dependencies = [
        ('participants', '0004_alter_penalty_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.CharField(
                choices=[('ABSOLUT', 'Absoluto'), ('VETERAN', 'Veterano'), ('SCHOOL', 'Escuela')], default='ABSOLUT', max_length=10
            ),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIX', 'Mixto')], default='MALE', max_length=10),
        ),
        migrations.RunPython(participant_classification, reverse_code=migrations.RunPython.noop),
    ]
