name: docker
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Decrypt environment file
        run: ./scripts/decrypt_env.sh
        env:
          ENV_DECODE_SECRET: ${{ secrets.ENV_DECODE_SECRET }}
      - name: Build images
        run: |
          docker buildx create --use --driver=docker-container
          docker buildx bake -f ./docker-compose.yml --set *.cache-to="type=gha,mode=max" --set *.cache-from="type=gha" --load
